### ISSUE TITLE
Change Colors

### ISSUE THREAD

**Issue by hellracer** [brandonxiang/leaflet.marker.highlight#5]
Hi,

Before anything i would like to say thanks for this awesome pllugins, may I ask is there anyway to change the colors on the fly? without hacking the CSS files directly? thanks again!!!

**Comment by brandonxiang** [comment]
Hacking css is the most simple way, but I will take it in consideration.

**Comment by roastedmonk** [comment]
Supported the feature given the pull request : https://github.com/brandonxiang/leaflet.marker.highlight/pull/6
