### ISSUE TITLE
how to use it in vue?

### ISSUE THREAD

**Issue by defineconst** [brandonxiang/leaflet.marker.highlight#7]
1、how to add it to map in vue？
2、how to remove it from map in vue？

**Comment by defineconst** [comment]
[https://www.cnblogs.com/defineconst/p/10494012.html](https://www.cnblogs.com/defineconst/p/10494012.html)

**Comment by LittleSisterMogu** [comment]
May I ask your help about how to use this on angular 7?Thank you~
